homepage:
    pattern:  /index
    defaults: { _controller: Projet1TestBundle:Test:index }

login:
    pattern:  /login
    defaults: { _controller: Projet1TestBundle:Test:Login }

showProfil:
    pattern:  /show
    defaults: { _controller: Projet1TestBundle:Test:showProfil }

ChangePassword:
    pattern:  /ChangePassword
    defaults: { _controller: Projet1TestBundle:Test:ChangePassword }

EditProfil:
    pattern:  /edit
    defaults: { _controller: Projet1TestBundle:Test:EditProfil }

admin:
    pattern:  /admin
    defaults: { _controller: Projet1TestBundle:Test:Admin }

Delete:
    pattern:  /delete/{id}
    defaults: { _controller: Projet1TestBundle:Test:Delete }
    requirements:
            id:  \d+